config/routes.rb
Spree::Core::Engine.add_routes do
  # Add your extension routes here
  namespace :admin do
  	resources :tags do 
      member do 
        put :download
      end
  	end
  end

  namespace :api, defaults: { format: 'json' } do
	  namespace :v1 do
	  	resources :tags
	  end
  end
end

app/models/spree/ProductDecorator.rb
module Spree
  module ProductDecorator
    def self.prepended(base)
      base.has_many :product_tags, dependent: :destroy
  	  base.has_many :tags, through: :product_tags
    end
  end
end

::Spree::Product.prepend(Spree::ProductDecorator)

app/models/spree/ProductTag.rb
class Spree::ProductTag < ActiveRecord::Base
  belongs_to :product
  belongs_to :tag
end

app/models/spree/Tag.rb
class Spree::Tag < ActiveRecord::Base
  has_many :product_tags, dependent: :destroy
  has_many :products, through: :product_tags
end

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator
    def self.prepended(base)
      base.has_many :product_tags, dependent: :destroy
  	  base.has_many :tags, through: :product_tags
    end
  end
end

::Spree::Product.prepend(Spree::ProductDecorator)

app/models/spree/product_tag.rb
class Spree::ProductTag < ActiveRecord::Base
  belongs_to :product
  belongs_to :tag
end

app/models/spree/tag_vendor_decorator.rb
module Spree
  module TagVendorDecorator
    def self.prepended(base)
      base.has_many :tags, class_name: "Spree::Tag", dependent: :destroy
    end
  end
end

::Spree::Vendor.prepend(::Spree::TagVendorDecorator)

app/controllers/spree/admin/products_controller_decorator.rb
module Spree::Admin::ProductsControllerDecorator
  def self.prepended(base)
    base.before_action :load_tags, only: [:new, :edit]
  end

  private

  def load_tags
    @tags = Spree::Tag.order(Arel.sql('LOWER(name)'))
  end
end

Spree::Admin::ProductsController.prepend Spree::Admin::ProductsControllerDecorator

app/controllers/spree/admin/tags_controller.rb
module Spree
  module Admin
    class TagsController < ResourceController
      helper Spree::ProductsHelper
      respond_to :html

      def index
        @tags = Spree::Tag.order(:id)
      end

      def show
        @products = @tag.products.includes([
            { 
              variants: [:images], 
              master: [:images, :default_price] 
            }
          ]).page(params[:page]).per(params[:per_page] || 50)
        
      end

      def download
        @products = @tag.products.includes([
          { 
            variants: [:images], 
            master: [:images, :default_price] 
          }
        ])
        file = Rails.root.join('storage', "#{@tag.name}_products.csv")
        CSV.open(file, "wb") do |csv|
          csv << ["name", "sku", "admin link", "page link"]
          @products.find_each do |product|
            product.variants_including_master.each do |variant|
              csv << [product.name, variant.sku, admin_product_url(product), product_url(product)]
            end
          end
        end
        send_file file, :type => 'text/csv', :disposition => 'attachment'
      end

    end
  end
end

app/controllers/spree/api/v1/tags_controller.rb
module Spree
  module Api
    module V1
      class TagsController < Spree::Api::BaseController
        def index
          @tags = if params[:ids]
                      Spree::Tag.accessible_by(current_ability).where(id: params[:ids].split(','))
                    else
                      Spree::Tag.accessible_by(current_ability).order(:id)
                    end

          @tags = @tags.ransack(params[:q]).result
          @tags = @tags.page(params[:page]).per(params[:per_page])
          respond_with(@tags)
        end
      end
    end
  end
end

app/views/spree/admin/tags/_form.html.erb
<div class="row">

  <div class="col-md-12">
    <%= f.field_container :name do %>
      <%= f.label :name, t(:name) %><br>
      <%= f.text_field :name, class: "form-control fullwidth" %>
    <% end %>
  </div>

</div>

app/views/spree/admin/tags/edit.html.erb
<% content_for :page_title do %>
  <%= t('editing_tag') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to t('back_to_tags'), spree.admin_tags_path, icon: 'arrow-left' %>
<% end %>

<%= render 'spree/shared/error_messages', target: @tag %>

<%= form_for [:admin, @tag] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div data-hook="admin_tags_method_edit_form_buttons">
      <%= render partial: 'spree/admin/shared/edit_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/tags/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to t('new_tag'), new_object_url, { class: 'btn-success', icon: 'add', id: 'admin_new_tag_link' } %>
<% end %>

<% content_for :page_title do %>
  <%= t('tag.title') %>
<% end %>

<table class="table" id="listing_tags" data-hook >
  <thead>
    <tr data-hook="admin_tags_index_headers">
      <th><%= Spree.t(:name) %></th>
      <th><%= Spree.t(:products) %></th>
      <th data-hook="admin_tags_index_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @tags.each do |tag|%>
    <tr>
      <% if can?(:edit, tag) %>
        <td class="align-center"><%= link_to tag.name, admin_tag_path(tag.id)  %></td>
      <% else %>
        <td class="align-center"><%= tag.name %></td>
      <% end %>
      <td class="align-center"><%= tag.products.length  %></td>
      <% if can?(:edit, tag) %>
        <td data-hook="admin_tags_index_row_actions" class="actions">
          <%= link_to_edit tag, no_text: true, class: 'edit' %>
          &nbsp;
          <%= link_to_delete tag, no_text: true %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/tags/new.html.erb
<% content_for :page_title do %>
  <%= t('new_tag') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to t('back_to_tags'), spree.admin_tags_path, icon: 'arrow-left' %>
<% end %>

<%= render 'spree/shared/error_messages', :target => @tag %>

<%= form_for [:admin, @tag] do |f| %>
  <fieldset class="no-border-top">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="clear"></div>

    <div data-hook="admin_tag_new_form_buttons">
      <%= render partial: 'spree/admin/shared/new_resource_links' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/tags/show.html.erb
<% content_for :page_title do %>
  <div class="col-xl-8">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-transparent">
        <li class="breadcrumb-item" aria-current="page"><%= link_to 'Tags', admin_tags_path %></li>
        <li class="breadcrumb-item active"><%= @tag.name %></li>
      </ol>
    </nav>
  </div>
  <div class="text-right">
    <%= link_to 'Download', download_admin_tag_path(@tag), method: :put, target: '_blank', class: 'btn btn-link'%>
  </div>
<% end %>

<% if @products.any? %>
<div class="table-responsive">
  <table class="table" id="listing_products">
    <thead>
      <tr data-hook="admin_products_index_headers">
        <th scope="col" colspan="2"><%= Spree.t(:name) %></th>
        <th scope="col"><%= Spree.t(:sku) %></th>
        <th scope="col"><%= Spree.t(:status) %></th>
        <th scope="col" class="text-center">
          <%=  Spree.t(:master_price) %>
        </th>
        <th scope="col" data-hook="admin_products_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <% available_status = available_status(product) %>
          <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows" class="<%= cycle('odd', 'even') %>">
            <td scope="row" class="image">
              <%= link_to edit_admin_product_path(product) do %>
                <%= mini_image product %>
              <% end %>
            </td>
            <td><%= link_to product.try(:name), edit_admin_product_path(product) %></td>
            <td class="sku"><%= product.sku rescue '' %></td>
            <td class="status"><%= active_badge(available_status == Spree.t(:available), label: available_status) %></td>
            <td class="text-center"><%= display_price(product) %></td>
            <td class="actions " data-hook="admin_products_index_row_actions">
              <span class="d-flex justify-content-end">
                <%= link_to_edit product, url: edit_admin_product_path(product), no_text: true, target: '_blank', class: 'edit' if can?(:edit, product) && !product.deleted? %>
              </span>
            </td>
          </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Product)) %>,
    <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Product) %>!
  </div>
<% end %>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @products } %>